I0628 17:55:38.099766 131503845316416 03_eval_finetuned.py:49] Loading finetuned model...
Traceback (most recent call last):
  File "/home/yunqiliu/octo/examples/03_eval_finetuned.py", line 120, in <module>
    app.run(main)
  File "/home/yunqiliu/anaconda3/envs/torch/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/yunqiliu/anaconda3/envs/torch/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/yunqiliu/octo/examples/03_eval_finetuned.py", line 50, in main
    model = OctoModel.load_pretrained("~/octo/checkpoint-40000")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yunqiliu/octo/examples/octo/model/octo_model_torch.py", line 43, in load_pretrained
    if "pred_horizon" in config["model"]["heads"]["action"]["kwargs"]:
                         ~~~~~~^^^^^^^^^
KeyError: 'model'